# -*- coding: utf-8 -*-
"""dashboard_vendas_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mdpBos3sIzA3XI9n7OqzkFniCN7VTbBH

# Dashboard de Vendas 2020 (versão de teste no Colab)
Visualização de Dados

## 1. Instalação
O Colab já vem com pandas, plotly e openpyxl. Falta só o Dash.
"""

!pip install -q dash

"""## 2. Envio da base
Clique em **Escolher arquivos** e selecione o Excel da base de vendas.
"""

from google.colab import files

enviado = files.upload()
NOME_ARQUIVO = next(iter(enviado))
print("Arquivo recebido:", NOME_ARQUIVO)

"""## 3. Carga e tratamento da base"""

import pandas as pd
import plotly.express as px
from dash import Dash, Input, Output, dash_table, dcc, html

# 1. CARGA E TRATAMENTO DA BASE
CAMINHO_BASE = NOME_ARQUIVO  # arquivo enviado na célula anterior

MESES = {1: "Jan", 2: "Fev", 3: "Mar", 4: "Abr", 5: "Mai", 6: "Jun",
         7: "Jul", 8: "Ago", 9: "Set", 10: "Out", 11: "Nov", 12: "Dez"}


def carregar_dados() -> pd.DataFrame:
    df = pd.read_excel(CAMINHO_BASE)

    # A planilha tem uma primeira coluna vazia ("Unnamed: 0"): removemos
    # todas as colunas sem nenhum valor.
    df = df.dropna(axis=1, how="all")

    # Espaços sobrando no texto (ex.: "Teclado " com espaço no final)
    colunas_texto = df.select_dtypes(include=["object", "string"]).columns
    for col in colunas_texto:
        df[col] = df[col].str.strip()

    # Padronização: Minas aparece como "MINAS" e os outros estados pela sigla
    df["Estado_Cliente"] = df["Estado_Cliente"].replace({"MINAS": "MG"})

    # Padronização dos nomes de clientes escritos em minúsculas
    df["Nome_Cliente"] = df["Nome_Cliente"].replace({"amazon": "Amazon",
                                                     "kabum": "KaBuM"})

    # Garante que só entram vendas de 2020 (a base já está toda em 2020,
    # mas o filtro deixa a regra explícita)
    df["Data_Pedido"] = pd.to_datetime(df["Data_Pedido"])
    df = df[df["Data_Pedido"].dt.year == 2020].copy()

    # Colunas de mês: o número serve para ordenar e o nome para exibir
    df["Mes_Num"] = df["Data_Pedido"].dt.month
    df["Mes"] = df["Mes_Num"].map(MESES)
    return df


df = carregar_dados()

"""### Verificações da base
Essas conferências justificam o tratamento feito acima.
"""

bruto = pd.read_excel(NOME_ARQUIVO)
print("Linhas e colunas da planilha original:", bruto.shape)
print("Colunas totalmente vazias:", [c for c in bruto.columns if bruto[c].isna().all()])
print("Estados antes do tratamento:", sorted(bruto["Estado_Cliente"].unique()))
print("Clientes antes do tratamento:", sorted(bruto["Nome_Cliente"].unique()))
print()
print("Linhas após o tratamento:", len(df))
print("Valores nulos:", int(df.isna().sum().sum()))
print("Pedidos duplicados:", int(df["ID_Pedido"].duplicated().sum()))
print("Período:", df["Data_Pedido"].min().date(), "a", df["Data_Pedido"].max().date())
confere = (df["Valor_Produto"] * df["Quantidade_Vendida"] == df["Valor_Total_Venda"]).all()
print("Valor_Produto x Quantidade = Valor_Total_Venda em todas as linhas:", confere)
print("Estados após o tratamento:", sorted(df["Estado_Cliente"].unique()))
df.head()

"""## 4. Funções auxiliares (formatação e estilo)"""

# 2. FUNÇÕES AUXILIARES
COR_PRINCIPAL = "#1D4E89"
COR_DESTAQUE = "#E8A33D"
PALETA = [COR_PRINCIPAL, COR_DESTAQUE, "#5B8DB8", "#9DB9D5", "#C9722C",
          "#7A8B99", "#2F7F6F", "#B5C99A"]
FONTE = '"Source Sans 3", "Segoe UI", Arial, sans-serif'


def reais(valor: float) -> str:
    """Formata um número no padrão brasileiro: R$ 1.234.567"""
    return "R$ " + f"{valor:,.0f}".replace(",", ".")


def estilizar(fig, titulo_y="Faturamento (R$)"):
    """Aplica o mesmo visual a todos os gráficos."""
    fig.update_layout(
        font_family=FONTE,
        font_color="#2B2F36",
        plot_bgcolor="white",
        paper_bgcolor="white",
        margin=dict(l=10, r=10, t=10, b=10),
        separators=",.",          # vírgula decimal e ponto de milhar
        hoverlabel=dict(font_family=FONTE),
        legend_title_text="",
        yaxis_title=titulo_y,
        xaxis_title="",
    )
    fig.update_xaxes(showgrid=False)
    fig.update_yaxes(gridcolor="#E6E9EE", tickprefix="R$ ")
    return fig


def figura_vazia(mensagem):
    """Gráfico em branco com uma mensagem, usado quando o filtro não tem dados."""
    fig = px.scatter()
    fig.update_layout(
        xaxis_visible=False, yaxis_visible=False,
        plot_bgcolor="white", paper_bgcolor="white",
        annotations=[dict(text=mensagem, showarrow=False,
                          font=dict(size=15, color="#7A8B99", family=FONTE))],
    )
    return fig


def total_por(dados, coluna):
    return (dados.groupby(coluna, as_index=False)["Valor_Total_Venda"].sum()
            .sort_values("Valor_Total_Venda", ascending=False))


def total_por_mes(dados):
    return (dados.groupby(["Mes_Num", "Mes"], as_index=False)["Valor_Total_Venda"]
            .sum().sort_values("Mes_Num"))


HOVER_REAIS = "%{x}<br>R$ %{y:,.2f}<extra></extra>"

"""## 5. Gráficos da parte 1 do roteiro
Cada gráfico aparece logo abaixo para conferência.
"""

# 3. GRÁFICOS FIXOS (PARTE 1 DO ROTEIRO)
# 3.1 Total de vendas por mês: gráfico de área
fig_mes = px.area(total_por_mes(df), x="Mes", y="Valor_Total_Venda",
                  markers=True, color_discrete_sequence=[COR_PRINCIPAL])
fig_mes.update_traces(hovertemplate=HOVER_REAIS)
estilizar(fig_mes)

# 3.2 Total de vendas por representante: barras horizontais ordenadas
dados_rep = total_por(df, "Nome_Representante").sort_values("Valor_Total_Venda")
fig_rep = px.bar(dados_rep, x="Valor_Total_Venda", y="Nome_Representante",
                 orientation="h", color_discrete_sequence=[COR_PRINCIPAL],
                 text="Valor_Total_Venda")
fig_rep.update_traces(texttemplate="R$ %{x:,.3s}", textposition="outside",
                      hovertemplate="%{y}<br>R$ %{x:,.2f}<extra></extra>",
                      cliponaxis=False)
estilizar(fig_rep, titulo_y="")
fig_rep.update_xaxes(tickprefix="R$ ", title="Faturamento (R$)", showgrid=True,
                     gridcolor="#E6E9EE",
                     # folga de 18% à direita para o rótulo da maior barra caber
                     range=[0, dados_rep["Valor_Total_Venda"].max() * 1.18])
fig_rep.update_yaxes(tickprefix="", gridcolor="white")

# 3.3 Total de vendas por regional: pizza (em formato de rosca)
fig_regional = px.pie(total_por(df, "Regional"), names="Regional",
                      values="Valor_Total_Venda", hole=0.45,
                      color_discrete_sequence=[COR_PRINCIPAL, COR_DESTAQUE])
fig_regional.update_traces(textinfo="label+percent",
                           hovertemplate="%{label}<br>R$ %{value:,.2f}<extra></extra>")
estilizar(fig_regional)
fig_regional.update_layout(showlegend=False)

# 3.4 Total de vendas por estado: barras verticais, coloridas pela regional
dados_estado = (df.groupby(["Estado_Cliente", "Regional"], as_index=False)
                ["Valor_Total_Venda"].sum()
                .sort_values("Valor_Total_Venda", ascending=False))
fig_estado = px.bar(dados_estado, x="Estado_Cliente", y="Valor_Total_Venda",
                    color="Regional",
                    color_discrete_map={"Sudeste": COR_PRINCIPAL,
                                        "Nordeste": COR_DESTAQUE})
fig_estado.update_traces(hovertemplate=HOVER_REAIS)
estilizar(fig_estado)
fig_estado.update_layout(legend=dict(orientation="h", y=1.08, x=0))

# 3.5 Total de vendas por produto: tabela
dados_produto = (df.groupby("Nome_Produto", as_index=False)
                 .agg(Quantidade=("Quantidade_Vendida", "sum"),
                      Faturamento=("Valor_Total_Venda", "sum"))
                 .sort_values("Faturamento", ascending=False))
dados_produto["Participação"] = (dados_produto["Faturamento"]
                                 / dados_produto["Faturamento"].sum() * 100)
tabela_produto = dash_table.DataTable(
    data=[
        {"Produto": r.Nome_Produto,
         "Unidades": f"{r.Quantidade:,}".replace(",", "."),
         "Faturamento": reais(r.Faturamento),
         "Participação": f"{r.Participação:.1f}%".replace(".", ",")}
        for r in dados_produto.itertuples()
    ],
    columns=[{"name": c, "id": c} for c in
             ["Produto", "Unidades", "Faturamento", "Participação"]],
    sort_action="native",
    style_as_list_view=True,
    style_table={"overflowX": "auto"},
    style_header={"fontWeight": "600", "backgroundColor": "#F2F4F7",
                  "borderBottom": f"2px solid {COR_PRINCIPAL}"},
    style_cell={"fontFamily": FONTE, "fontSize": 14, "padding": "8px 10px",
                "textAlign": "left"},
    style_cell_conditional=[{"if": {"column_id": c}, "textAlign": "right"}
                            for c in ["Unidades", "Faturamento", "Participação"]],
)

# Indicadores do topo
faturamento_total = df["Valor_Total_Venda"].sum()
total_pedidos = df["ID_Pedido"].nunique()
indicadores = [
    ("Faturamento em 2020", reais(faturamento_total)),
    ("Pedidos", f"{total_pedidos:,}".replace(",", ".")),
    ("Ticket médio", reais(faturamento_total / total_pedidos)),
    ("Unidades vendidas", f"{df['Quantidade_Vendida'].sum():,}".replace(",", ".")),
]

fig_mes.show()

fig_rep.show()

fig_regional.show()

fig_estado.show()

# Prévia da tabela de produtos (no painel ela aparece como DataTable do Dash)
dados_produto.style.format({"Faturamento": lambda v: reais(v),
                            "Participação": "{:.1f}%"}).hide(axis="index")

"""## 6. Estilo visual do painel
O Dash carrega automaticamente os arquivos CSS da pasta `assets`.
"""

import os

os.makedirs("assets", exist_ok=True)
with open("assets/estilo.css", "w", encoding="utf-8") as arquivo:
    arquivo.write("""@import url("https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@400;600;700&display=swap");

:root {
  --azul: #1D4E89;
  --ambar: #E8A33D;
  --texto: #2B2F36;
  --texto-suave: #6B7684;
  --fundo: #EEF1F5;
  --borda: #DDE2E8;
}

* { box-sizing: border-box; }

body {
  margin: 0;
  background: var(--fundo);
  color: var(--texto);
  font-family: "Source Sans 3", "Segoe UI", Arial, sans-serif;
  font-size: 16px;
  line-height: 1.5;
}

.pagina { max-width: 1280px; margin: 0 auto; padding: 0 24px 40px; }

/* Cabeçalho: faixa azul com os indicadores do ano */
.cabecalho {
  background: var(--azul);
  color: white;
  margin: 0 -24px 32px;
  padding: 36px 24px 28px;
  display: flex;
  flex-wrap: wrap;
  gap: 28px;
  justify-content: space-between;
  align-items: flex-end;
}
.cabecalho h1 { margin: 0 0 6px; font-size: 2.2rem; font-weight: 700; line-height: 1.15; }
.cabecalho p { margin: 0; max-width: 46ch; color: #C9D6E6; }

.indicadores { display: flex; flex-wrap: wrap; gap: 32px; }
.indicador { display: flex; flex-direction: column; border-left: 3px solid var(--ambar); padding-left: 12px; }
.indicador .valor { font-size: 1.5rem; font-weight: 700; font-variant-numeric: tabular-nums; }
.indicador .legenda { font-size: 0.9rem; color: #C9D6E6; }

/* Seções e grade de cartões */
.secao { margin-bottom: 36px; }
.secao h2 { font-size: 1.35rem; font-weight: 700; margin: 0 0 14px; }

.grade { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 20px; }

.cartao {
  background: white;
  border: 1px solid var(--borda);
  border-radius: 6px;
  padding: 18px 20px;
  min-width: 0;
}
.cartao.largo { grid-column: 1 / -1; }
.cartao h3 { margin: 0 0 4px; font-size: 1.05rem; font-weight: 600; }
.subtitulo { margin: 0 0 10px; color: var(--texto-suave); font-size: 0.92rem; }

/* Filtros */
.filtros-linha { display: flex; flex-wrap: wrap; gap: 16px; }
.filtros-linha .filtro { flex: 1 1 220px; }
.filtro { display: block; margin: 10px 0 8px; }
.rotulo-filtro { display: block; font-size: 0.88rem; font-weight: 600; color: var(--texto-suave); margin-bottom: 4px; }
.radio label { margin-right: 14px; cursor: pointer; }
.radio input { margin-right: 5px; accent-color: var(--azul); }

.rodape { color: var(--texto-suave); font-size: 0.85rem; padding-top: 8px; border-top: 1px solid var(--borda); }

@media (max-width: 860px) {
  .grade { grid-template-columns: 1fr; }
  .cabecalho h1 { font-size: 1.8rem; }
}
""")
print("assets/estilo.css criado")

"""## 7. Layout do painel"""

# 4. LAYOUT
app = Dash(__name__, title="Vendas 2020")
server = app.server  # usado pelo gunicorn no deploy


def opcoes(coluna):
    return [{"label": v, "value": v} for v in sorted(df[coluna].unique())]


def cartao(titulo, conteudo, subtitulo=None, classe="cartao"):
    filhos = [html.H3(titulo)]
    if subtitulo:
        filhos.append(html.P(subtitulo, className="subtitulo"))
    filhos.append(conteudo)
    return html.Div(filhos, className=classe)


def grafico(fig=None, id=None, altura=320):
    props = {"config": {"displayModeBar": False, "locale": "pt-BR"},
             "style": {"height": f"{altura}px"}}
    if id:
        props["id"] = id
    if fig is not None:
        props["figure"] = fig
    return dcc.Graph(**props)


def filtro(rotulo, componente):
    return html.Label([html.Span(rotulo, className="rotulo-filtro"), componente],
                      className="filtro")


app.layout = html.Div(className="pagina", children=[

    html.Header(className="cabecalho", children=[
        html.Div([
            html.H1("Desempenho de vendas 2020"),
            html.P("Relatório para a diretoria comercial: faturamento por período, "
                   "equipe, produto e região."),
        ]),
        html.Div(className="indicadores", children=[
            html.Div([html.Span(v, className="valor"), html.Span(t, className="legenda")],
                     className="indicador")
            for t, v in indicadores
        ]),
    ]),

    # ---- Parte 1: visão geral ------------------------------------------
    html.Section(className="secao", children=[
        html.H2("Visão geral do ano"),
        html.Div(className="grade", children=[
            cartao("Faturamento por mês", grafico(fig_mes), classe="cartao largo"),
            cartao("Faturamento por representante", grafico(fig_rep, altura=360)),
            cartao("Faturamento por regional", grafico(fig_regional, altura=360)),
            cartao("Faturamento por estado", grafico(fig_estado, altura=360)),
            cartao("Faturamento por produto", tabela_produto,
                   subtitulo="Clique no nome da coluna para ordenar."),
        ]),
    ]),

    # ---- Parte 2: gráficos com filtros ---------------------------------
    html.Section(className="secao", children=[
        html.H2("Análises com filtros"),
        html.Div(className="grade", children=[

            cartao("Produtos mais vendidos no período", html.Div([
                filtro("Mês", dcc.Dropdown(
                    id="filtro-mes",
                    options=[{"label": MESES[m], "value": m} for m in range(1, 13)],
                    multi=True, placeholder="Todos os meses")),
                grafico(id="graf-produtos-mes", altura=380),
            ])),

            cartao("Evolução mensal do representante", html.Div([
                filtro("Representante", dcc.Dropdown(
                    id="filtro-representante", options=opcoes("Nome_Representante"),
                    value=df["Nome_Representante"].value_counts().idxmax(),
                    clearable=False)),
                grafico(id="graf-representante-mes", altura=380),
            ])),

            cartao("Produtos comprados por cliente", html.Div([
                html.Div(className="filtros-linha", children=[
                    filtro("Cliente", dcc.Dropdown(
                        id="filtro-cliente", options=opcoes("Nome_Cliente"),
                        value="Amazon", clearable=False)),
                    filtro("Regional", dcc.RadioItems(
                        id="filtro-regional",
                        options=[{"label": "Todas", "value": "Todas"}] + opcoes("Regional"),
                        value="Todas", inline=True, className="radio")),
                ]),
                grafico(id="graf-cliente-produto", altura=380),
            ]), classe="cartao largo"),
        ]),
    ]),

    # ---- Parte 3: filtro encadeado Estado -> Cidade ---------------------
    html.Section(className="secao", children=[
        html.H2("Vendas por localidade do cliente"),
        cartao("Faturamento por cliente na cidade", html.Div([
            html.Div(className="filtros-linha", children=[
                filtro("Estado", dcc.Dropdown(
                    id="filtro-estado", options=opcoes("Estado_Cliente"),
                    value="MG", clearable=False)),
                filtro("Cidade", dcc.Dropdown(
                    id="filtro-cidade", placeholder="Todas as cidades do estado")),
            ]),
            grafico(id="graf-cidade", altura=380),
        ]), subtitulo="Escolha o estado; a lista de cidades mostra apenas as "
                      "cidades daquele estado.", classe="cartao largo"),
    ]),

    html.Footer("Fonte: base de vendas 2020 fornecida na disciplina de "
                "Visualização de Dados, IF Sudeste MG, Campus Muriaé.",
                className="rodape"),
])

"""## 8. Callbacks (partes 2 e 3 do roteiro)"""

# 5. CALLBACKS

# Parte 2, gráfico 1: filtro de Mês -> faturamento por produto
@app.callback(Output("graf-produtos-mes", "figure"),
              Input("filtro-mes", "value"))
def atualizar_produtos_mes(meses):
    dados = df[df["Mes_Num"].isin(meses)] if meses else df
    agrupado = total_por(dados, "Nome_Produto").head(10).sort_values("Valor_Total_Venda")
    fig = px.bar(agrupado, x="Valor_Total_Venda", y="Nome_Produto", orientation="h",
                 color_discrete_sequence=[COR_PRINCIPAL])
    fig.update_traces(hovertemplate="%{y}<br>R$ %{x:,.2f}<extra></extra>")
    estilizar(fig, titulo_y="")
    fig.update_xaxes(tickprefix="R$ ", showgrid=True, gridcolor="#E6E9EE")
    fig.update_yaxes(tickprefix="", gridcolor="white")
    return fig


# Parte 2, gráfico 2: filtro de Representante -> faturamento mês a mês,
# comparado com a média da equipe
@app.callback(Output("graf-representante-mes", "figure"),
              Input("filtro-representante", "value"))
def atualizar_representante(representante):
    do_rep = total_por_mes(df[df["Nome_Representante"] == representante])
    do_rep["Série"] = representante

    media = total_por_mes(df)
    media["Valor_Total_Venda"] = media["Valor_Total_Venda"] / df["Nome_Representante"].nunique()
    media["Série"] = "Média da equipe"

    fig = px.line(pd.concat([do_rep, media]), x="Mes", y="Valor_Total_Venda",
                  color="Série", markers=True, line_dash="Série",
                  color_discrete_sequence=[COR_PRINCIPAL, "#9AA5B1"],
                  line_dash_sequence=["solid", "dot"])
    fig.update_traces(hovertemplate=HOVER_REAIS)
    estilizar(fig)
    fig.update_layout(legend=dict(orientation="h", y=1.1, x=0))
    return fig


# Parte 2, gráfico 3: filtros de Cliente e Regional -> faturamento por produto
@app.callback(Output("graf-cliente-produto", "figure"),
              Input("filtro-cliente", "value"),
              Input("filtro-regional", "value"))
def atualizar_cliente(cliente, regional):
    dados = df[df["Nome_Cliente"] == cliente]
    if regional != "Todas":
        dados = dados[dados["Regional"] == regional]
    if dados.empty:
        return figura_vazia(f"Nenhuma venda para {cliente} nesta regional.")

    agrupado = total_por(dados, "Nome_Produto").sort_values("Valor_Total_Venda")
    fig = px.bar(agrupado, x="Valor_Total_Venda", y="Nome_Produto", orientation="h",
                 color_discrete_sequence=[COR_DESTAQUE])
    fig.update_traces(hovertemplate="%{y}<br>R$ %{x:,.2f}<extra></extra>")
    estilizar(fig, titulo_y="")
    fig.update_xaxes(tickprefix="R$ ", showgrid=True, gridcolor="#E6E9EE")
    fig.update_yaxes(tickprefix="", gridcolor="white")
    return fig


# Parte 3, filtro encadeado (passo 1): o Estado define as opções de Cidade.
# O valor volta para None para não manter selecionada uma cidade de outro estado.
@app.callback(Output("filtro-cidade", "options"),
              Output("filtro-cidade", "value"),
              Input("filtro-estado", "value"))
def atualizar_cidades(estado):
    cidades = sorted(df.loc[df["Estado_Cliente"] == estado, "Cidade_Cliente"].unique())
    return [{"label": c, "value": c} for c in cidades], None


# Parte 3, filtro encadeado (passo 2): Estado + Cidade -> faturamento por cliente
@app.callback(Output("graf-cidade", "figure"),
              Input("filtro-estado", "value"),
              Input("filtro-cidade", "value"))
def atualizar_grafico_cidade(estado, cidade):
    dados = df[df["Estado_Cliente"] == estado]
    if cidade:
        dados = dados[dados["Cidade_Cliente"] == cidade]

    agrupado = (dados.groupby(["Nome_Cliente", "Cidade_Cliente"], as_index=False)
                ["Valor_Total_Venda"].sum()
                .sort_values("Valor_Total_Venda", ascending=False))
    # Ordena os clientes pelo total somado de todas as cidades
    ordem = total_por(dados, "Nome_Cliente")["Nome_Cliente"].tolist()
    fig = px.bar(agrupado, x="Nome_Cliente", y="Valor_Total_Venda",
                 color="Cidade_Cliente", barmode="group",
                 category_orders={"Nome_Cliente": ordem},
                 color_discrete_sequence=[COR_PRINCIPAL, COR_DESTAQUE])
    fig.update_traces(hovertemplate="%{x}<br>R$ %{y:,.2f}<extra></extra>")
    estilizar(fig)
    fig.update_layout(legend=dict(orientation="h", y=1.1, x=0))
    return fig

"""## 9. Rodar o painel
O painel aparece abaixo da célula. Se ficar em branco, troque `"inline"` por `"external"`
e clique no link que aparecer para abrir o painel em outra aba.

Para parar o painel, interrompa a célula (botão de parar) ou reinicie o ambiente.
Se alterar alguma célula anterior, rode de novo a partir dela até esta.
"""

app.run(jupyter_mode="inline", height=2600)